import type { Metadata } from "next";
import EmployeeTemplate from "@/components/employee template";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EmployeeTemplate>{children}</EmployeeTemplate>
  );
}
